version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/diskscribe-2026-desktop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      desktop-npm-prod:
        dependency-type: "production"
      desktop-npm-dev:
        dependency-type: "development"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
